/** Representative size and floor count per building type, shared by the
 * coherence test and diagnostics so both measure the same scenarios. */
export const SCENARIOS: Record<string, { target: number; floors: number }> = {
  sl_il: { target: 120, floors: 4 }, sl_al: { target: 80, floors: 3 },
  sl_mc: { target: 40, floors: 1 }, sl_snf: { target: 90, floors: 2 },
  sl_ccrc: { target: 220, floors: 4 }, sl_affordable: { target: 80, floors: 4 },
  hc_mob: { target: 60_000, floors: 3 }, hc_asc: { target: 4, floors: 1 },
  hc_clinic: { target: 20, floors: 1 }, hc_bedtower: { target: 120, floors: 6 },
  hc_ed: { target: 24, floors: 1 }, hc_imaging: { target: 4, floors: 1 },
  hc_behavioral: { target: 48, floors: 2 },
  he_residence: { target: 400, floors: 5 }, he_academic: { target: 60_000, floors: 3 },
  he_lab: { target: 80_000, floors: 3 }, he_student_life: { target: 50_000, floors: 2 },
  he_athletics: { target: 90_000, floors: 2 }, he_library: { target: 70_000, floors: 3 },
  mf_garden: { target: 100, floors: 3 }, mf_wrap: { target: 200, floors: 5 },
  mf_podium: { target: 180, floors: 6 }, mf_highrise: { target: 250, floors: 18 },
  mf_affordable: { target: 90, floors: 4 }, mf_townhome: { target: 40, floors: 3 },
  hp_select: { target: 120, floors: 5 }, hp_extended: { target: 110, floors: 4 },
  hp_full: { target: 250, floors: 8 }, hp_boutique: { target: 90, floors: 6 },
  wk_shell: { target: 90_000, floors: 4 }, wk_fitout: { target: 30_000, floors: 1 },
  wk_flex: { target: 60_000, floors: 1 },
  in_warehouse: { target: 250_000, floors: 1 }, in_manufacturing: { target: 120_000, floors: 1 },
  in_cold: { target: 150_000, floors: 1 },
  cv_k12: { target: 900, floors: 2 }, cv_worship: { target: 700, floors: 1 },
  cv_municipal: { target: 30_000, floors: 2 }, cv_recreation: { target: 60_000, floors: 1 },
  pk_garage: { target: 400, floors: 5 }, pk_below: { target: 200, floors: 2 },
  pk_surface: { target: 300, floors: 1 },
};
