import type { BuildingTypeDef } from "./types";

/**
 * Building types — the second axis you iterate on.
 *
 * Each entry is a seed, not a cage: it sets a defensible starting massing,
 * program mix, and efficiency band for the type, all of which the user edits.
 * `unitRefs` and `programMix` point at the unit catalog by `ref`.
 */
export const BUILDING_TYPES: BuildingTypeDef[] = [
  // ===================== SENIOR LIVING =====================
  {
    id: "sl_il",
    marketId: "senior_living",
    label: "Independent Living",
    short: "IL",
    description: "Apartment-style senior housing with full kitchens, congregate dining, and wellness amenity.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "senior_independent",
      floors: 4, floorToFloor: 10.5, footprint: { w: 200, d: 68 }, grossing: 1.35,
      glazing: "punched", glazingCoverage: 34, skin: "fiber_cement", roof: "flat",
      structure: "wood_frame", travelDistance: 250, bay: { w: 26, d: 30 }, parkingRatio: 1.1,
    },
    plan: "U",
    features: [
      { kind: "porte_cochere", params: { width: 36, projection: 22, height: 15 } },
      { kind: "lobby", params: { width: 40, projection: 7, floors: 2 } },
      { kind: "bay", params: { width: 14, projection: 3 } },
    ],
    efficiency: { low: 0.68, typical: 0.74, high: 0.79 },
    unitRefs: ["il_studio", "il_1br", "il_1br_den", "il_2br", "il_2br_den", "il_cottage"],
    programMix: [
      { unitRef: "il_1br", share: 0.4 },
      { unitRef: "il_1br_den", share: 0.15 },
      { unitRef: "il_2br", share: 0.3 },
      { unitRef: "il_2br_den", share: 0.1 },
      { unitRef: "il_studio", share: 0.05 },
    ],
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 26 },
      { unitRef: "amen_kitchen", sfPerCapacity: 12 },
      { unitRef: "amen_wellness", sfPerCapacity: 18 },
      { unitRef: "amen_bistro", sfPerCapacity: 7 },
      { unitRef: "amen_lobby", sfPerCapacity: 9 },
    ],
    typicalCapacity: { low: 60, high: 220 },
    tags: ["unit-driven", "amenity-heavy"],
  },
  {
    id: "sl_al",
    marketId: "senior_living",
    label: "Assisted Living",
    short: "AL",
    description: "Licensed personal-care suites with kitchenettes, three-meal dining, and staff support cores.",
    capacityUom: "UNIT",
    capacityLabel: "suites",
    defaults: {
      costProfile: "senior_licensed",
      floors: 3, floorToFloor: 10, footprint: { w: 175, d: 66 }, grossing: 1.45,
      glazing: "punched", glazingCoverage: 30, skin: "fiber_cement", roof: "flat",
      structure: "wood_frame", travelDistance: 200, bay: { w: 22, d: 28 }, parkingRatio: 0.5,
    },
    features: [
      { kind: "canopy", params: { width: 26, projection: 10, support: "column" } },
      { kind: "lobby", params: { width: 34, projection: 6, floors: 1 } },
    ],
    efficiency: { low: 0.62, typical: 0.68, high: 0.73 },
    unitRefs: ["al_studio", "al_1br", "al_companion"],
    programMix: [
      { unitRef: "al_studio", share: 0.55 },
      { unitRef: "al_1br", share: 0.35 },
      { unitRef: "al_companion", share: 0.1 },
    ],
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 32 },
      { unitRef: "amen_kitchen", sfPerCapacity: 16 },
      { unitRef: "sup_nurse", sfPerCapacity: 10 },
      { unitRef: "amen_salon", sfPerCapacity: 4 },
    ],
    typicalCapacity: { low: 40, high: 120 },
    tags: ["licensed", "unit-driven"],
  },
  {
    id: "sl_mc",
    marketId: "senior_living",
    label: "Memory Care",
    short: "MC",
    description: "Secured households for cognitive care — small clusters, controlled egress, high staff ratios.",
    capacityUom: "UNIT",
    capacityLabel: "rooms",
    defaults: {
      costProfile: "senior_licensed",
      floors: 1, floorToFloor: 11, footprint: { w: 150, d: 90 }, grossing: 1.55,
      glazing: "punched", glazingCoverage: 26, skin: "fiber_cement", roof: "gable",
      structure: "wood_frame", travelDistance: 200, parkingRatio: 0.4,
    },
    plan: "courtyard",
    features: [
      { kind: "canopy", params: { width: 20, projection: 8 } },
    ],
    efficiency: { low: 0.55, typical: 0.62, high: 0.68 },
    unitRefs: ["mc_private", "mc_companion"],
    programMix: [
      { unitRef: "mc_private", share: 0.8 },
      { unitRef: "mc_companion", share: 0.2 },
    ],
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 38 },
      { unitRef: "sup_nurse", sfPerCapacity: 14 },
      { unitRef: "amen_activity", sfPerCapacity: 22 },
    ],
    typicalCapacity: { low: 16, high: 64 },
    tags: ["licensed", "secured", "single-story"],
  },
  {
    id: "sl_snf",
    marketId: "senior_living",
    label: "Skilled Nursing",
    short: "SNF",
    description: "Licensed nursing beds with clinical support, therapy gym, and commercial dietary.",
    capacityUom: "BED",
    capacityLabel: "beds",
    defaults: {
      costProfile: "skilled_nursing",
      floors: 2, floorToFloor: 12, footprint: { w: 190, d: 80 }, grossing: 1.6,
      glazing: "punched", glazingCoverage: 28, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 200, parkingRatio: 0.45,
    },
    features: [
      { kind: "canopy", params: { width: 24, projection: 10, support: "column" } },
    ],
    efficiency: { low: 0.5, typical: 0.58, high: 0.64 },
    unitRefs: ["snf_private", "snf_semi"],
    programMix: [
      { unitRef: "snf_private", share: 0.7 },
      { unitRef: "snf_semi", share: 0.3 },
    ],
    supportSpaces: [
      { unitRef: "sup_nurse", sfPerCapacity: 22 },
      { unitRef: "amen_dining", sfPerCapacity: 28 },
      { unitRef: "amen_kitchen", sfPerCapacity: 18 },
      { unitRef: "clin_pt", sfPerCapacity: 16 },
    ],
    typicalCapacity: { low: 40, high: 160 },
    tags: ["licensed", "clinical"],
  },
  {
    id: "sl_ccrc",
    marketId: "senior_living",
    label: "Life Plan Campus (CCRC)",
    short: "LPC",
    description: "Multi-building campus blending IL, AL, MC, and SNF with a shared commons and back-of-house.",
    capacityUom: "UNIT",
    capacityLabel: "units",
    defaults: {
      costProfile: "senior_licensed",
      floors: 4, floorToFloor: 10.5, footprint: { w: 210, d: 70 }, grossing: 1.42,
      glazing: "punched", glazingCoverage: 32, skin: "brick", roof: "flat",
      structure: "podium", travelDistance: 250, parkingRatio: 0.9,
    },
    plan: "U",
    features: [
      { kind: "porte_cochere", params: { width: 40, projection: 24 } },
      { kind: "lobby", params: { width: 50, projection: 8, floors: 2 } },
    ],
    efficiency: { low: 0.63, typical: 0.7, high: 0.76 },
    unitRefs: ["il_1br", "il_2br", "al_studio", "al_1br", "mc_private", "snf_private"],
    programMix: [
      { unitRef: "il_1br", share: 0.34 },
      { unitRef: "il_2br", share: 0.26 },
      { unitRef: "al_studio", share: 0.16 },
      { unitRef: "al_1br", share: 0.1 },
      { unitRef: "mc_private", share: 0.08 },
      { unitRef: "snf_private", share: 0.06 },
    ],
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 30 },
      { unitRef: "amen_kitchen", sfPerCapacity: 15 },
      { unitRef: "amen_wellness", sfPerCapacity: 20 },
      { unitRef: "amen_theater", sfPerCapacity: 8 },
      { unitRef: "amen_lobby", sfPerCapacity: 10 },
    ],
    typicalCapacity: { low: 120, high: 450 },
    tags: ["campus", "multi-building", "phased"],
  },
  {
    id: "sl_affordable",
    marketId: "senior_living",
    label: "Affordable Senior (LIHTC)",
    short: "SL-A",
    description: "Tax-credit senior housing. Cost caps and QAP scoring drive a lean amenity and finish package.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "wood_residential",
      floors: 4, floorToFloor: 9.5, footprint: { w: 180, d: 62 }, grossing: 1.28,
      glazing: "punched", glazingCoverage: 26, skin: "fiber_cement", roof: "flat",
      structure: "wood_frame", travelDistance: 250, parkingRatio: 0.7,
    },
    efficiency: { low: 0.74, typical: 0.79, high: 0.84 },
    unitRefs: ["il_studio", "il_1br", "il_2br"],
    programMix: [
      { unitRef: "il_1br", share: 0.7 },
      { unitRef: "il_2br", share: 0.2 },
      { unitRef: "il_studio", share: 0.1 },
    ],
    supportSpaces: [
      { unitRef: "amen_community", sfPerCapacity: 12 },
      { unitRef: "amen_lobby", sfPerCapacity: 5 },
    ],
    typicalCapacity: { low: 40, high: 120 },
    tags: ["LIHTC", "cost-capped"],
  },

  // ===================== HEALTHCARE =====================
  {
    id: "hc_mob",
    marketId: "healthcare",
    label: "Medical Office Building",
    short: "MOB",
    description: "Multi-tenant outpatient shell with clinic fit-outs. Shell and TI usually priced separately.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "healthcare_mob",
      floors: 3, floorToFloor: 14, footprint: { w: 160, d: 90 }, grossing: 1.42,
      glazing: "strip", glazingCoverage: 55, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 250, bay: { w: 30, d: 30 }, parkingRatio: 0,
    },
    plan: "L",
    features: [
      { kind: "canopy", params: { width: 28, projection: 9, height: 13 } },
      { kind: "lobby", params: { width: 44, projection: 7, floors: 2 } },
      { kind: "sunshade", params: { coverage: 0.85, projection: 3 } },
      { kind: "roof_screen", params: { coverage: 0.5, material: "louver" } },
    ],
    efficiency: { low: 0.6, typical: 0.68, high: 0.74 },
    unitRefs: ["exam_op", "clin_proc", "clin_lab", "clin_imaging_ct", "off_private", "amen_lobby"],
    programMix: [
      { unitRef: "exam_op", share: 0.62 },
      { unitRef: "clin_proc", share: 0.12 },
      { unitRef: "off_private", share: 0.18 },
      { unitRef: "clin_lab", share: 0.08 },
    ],
    typicalCapacity: { low: 20000, high: 120000 },
    tags: ["outpatient", "shell-and-TI"],
  },
  {
    id: "hc_asc",
    marketId: "healthcare",
    label: "Ambulatory Surgery Center",
    short: "ASC",
    description: "Licensed outpatient ORs with pre-op/PACU bays, sterile processing, and dedicated air handling.",
    capacityUom: "EA",
    capacityLabel: "operating rooms",
    defaults: {
      costProfile: "healthcare_acute",
      floors: 1, floorToFloor: 16, footprint: { w: 150, d: 110 }, grossing: 1.65,
      glazing: "punched", glazingCoverage: 24, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 200, parkingRatio: 0,
    },
    features: [
      { kind: "porte_cochere", params: { width: 34, projection: 20, height: 15 } },
      { kind: "lobby", params: { width: 32, projection: 6, floors: 1 } },
    ],
    efficiency: { low: 0.48, typical: 0.56, high: 0.62 },
    unitRefs: ["or_general", "or_specialty", "clin_prepop", "clin_sterile", "exam_op"],
    programMix: [
      { unitRef: "or_general", share: 0.75 },
      { unitRef: "or_specialty", share: 0.25 },
    ],
    supportSpaces: [
      { unitRef: "clin_prepop", sfPerCapacity: 720 },
      { unitRef: "clin_sterile", sfPerCapacity: 320 },
    ],
    typicalCapacity: { low: 2, high: 8 },
    tags: ["licensed", "high-MEP"],
  },
  {
    id: "hc_clinic",
    marketId: "healthcare",
    label: "Outpatient Clinic",
    short: "CLIN",
    description: "Primary or specialty care clinic — exam-room driven, modest infrastructure, fast delivery.",
    capacityUom: "EA",
    capacityLabel: "exam rooms",
    defaults: {
      costProfile: "healthcare_outpatient",
      floors: 1, floorToFloor: 13, footprint: { w: 130, d: 80 }, grossing: 1.4,
      glazing: "strip", glazingCoverage: 45, skin: "fiber_cement", roof: "flat",
      structure: "light_gauge", travelDistance: 250, parkingRatio: 0,
    },
    features: [
      { kind: "canopy", params: { width: 22, projection: 8 } },
      { kind: "lobby", params: { width: 28, projection: 5, floors: 1 } },
    ],
    efficiency: { low: 0.6, typical: 0.66, high: 0.72 },
    unitRefs: ["exam_op", "clin_proc", "clin_lab", "off_private"],
    programMix: [
      { unitRef: "exam_op", share: 0.8 },
      { unitRef: "clin_proc", share: 0.1 },
      { unitRef: "clin_lab", share: 0.1 },
    ],
    typicalCapacity: { low: 6, high: 40 },
    tags: ["outpatient"],
  },
  {
    id: "hc_bedtower",
    marketId: "healthcare",
    label: "Inpatient Bed Tower",
    short: "TOWER",
    description: "Acute-care nursing units stacked over a support podium. The most infrastructure-intensive type.",
    capacityUom: "BED",
    capacityLabel: "beds",
    defaults: {
      costProfile: "healthcare_acute",
      floors: 6, floorToFloor: 15, footprint: { w: 200, d: 96 }, grossing: 1.85,
      glazing: "strip", glazingCoverage: 48, skin: "precast", roof: "flat",
      structure: "concrete", travelDistance: 200, bay: { w: 30, d: 32 }, highRise: true,
    },
    features: [
      { kind: "porte_cochere", params: { width: 46, projection: 26, height: 16 } },
      { kind: "lobby", params: { width: 60, projection: 8, floors: 2 } },
      { kind: "roof_screen", params: { coverage: 0.8, material: "panel", height: 12 } },
    ],
    efficiency: { low: 0.42, typical: 0.52, high: 0.58 },
    unitRefs: ["bed_medsurg", "bed_icu", "clin_ldr", "sup_nurse"],
    programMix: [
      { unitRef: "bed_medsurg", share: 0.78 },
      { unitRef: "bed_icu", share: 0.22 },
    ],
    supportSpaces: [{ unitRef: "sup_nurse", sfPerCapacity: 44 }],
    typicalCapacity: { low: 60, high: 320 },
    tags: ["acute", "high-MEP", "high-rise"],
  },
  {
    id: "hc_ed",
    marketId: "healthcare",
    label: "Emergency Department",
    short: "ED",
    description: "Treatment bays with trauma, triage, and imaging adjacency. 24/7 redundancy on every system.",
    capacityUom: "EA",
    capacityLabel: "treatment bays",
    defaults: {
      costProfile: "healthcare_acute",
      floors: 1, floorToFloor: 16, footprint: { w: 170, d: 120 }, grossing: 1.8,
      glazing: "punched", glazingCoverage: 22, skin: "precast", roof: "flat",
      structure: "steel", travelDistance: 200,
    },
    features: [
      { kind: "porte_cochere", params: { width: 40, projection: 26, height: 16 } },
      { kind: "roof_screen", params: { coverage: 0.7, material: "panel" } },
    ],
    efficiency: { low: 0.44, typical: 0.52, high: 0.58 },
    unitRefs: ["ed_bay", "clin_trauma", "clin_imaging_ct", "sup_nurse"],
    programMix: [
      { unitRef: "ed_bay", share: 0.85 },
      { unitRef: "clin_trauma", share: 0.15 },
    ],
    typicalCapacity: { low: 8, high: 60 },
    tags: ["acute", "24-7"],
  },
  {
    id: "hc_imaging",
    marketId: "healthcare",
    label: "Imaging Center",
    short: "IMG",
    description: "Diagnostic imaging — CT, MRI, and ultrasound. Shielding, structure, and power dominate cost.",
    capacityUom: "EA",
    capacityLabel: "modalities",
    defaults: {
      costProfile: "healthcare_outpatient",
      floors: 1, floorToFloor: 15, footprint: { w: 120, d: 80 }, grossing: 1.55,
      glazing: "punched", glazingCoverage: 20, skin: "fiber_cement", roof: "flat",
      structure: "steel", travelDistance: 250,
    },
    efficiency: { low: 0.5, typical: 0.58, high: 0.64 },
    unitRefs: ["clin_imaging_ct", "clin_imaging_mri", "exam_op"],
    programMix: [
      { unitRef: "clin_imaging_ct", share: 0.55 },
      { unitRef: "clin_imaging_mri", share: 0.45 },
    ],
    typicalCapacity: { low: 2, high: 10 },
    tags: ["equipment-driven", "shielding"],
  },
  {
    id: "hc_behavioral",
    marketId: "healthcare",
    label: "Behavioral Health",
    short: "BH",
    description: "Inpatient behavioral beds — ligature-resistant detailing throughout, secured circulation.",
    capacityUom: "BED",
    capacityLabel: "beds",
    defaults: {
      costProfile: "healthcare_inpatient",
      floors: 2, floorToFloor: 13, footprint: { w: 180, d: 84 }, grossing: 1.65,
      glazing: "punched", glazingCoverage: 22, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 200,
    },
    efficiency: { low: 0.48, typical: 0.56, high: 0.62 },
    unitRefs: ["bh_room", "sup_nurse", "amen_activity"],
    programMix: [{ unitRef: "bh_room", share: 1 }],
    supportSpaces: [
      { unitRef: "sup_nurse", sfPerCapacity: 30 },
      { unitRef: "amen_activity", sfPerCapacity: 26 },
    ],
    typicalCapacity: { low: 16, high: 100 },
    tags: ["licensed", "ligature-resistant", "secured"],
  },
  // ===================== HIGHER EDUCATION =====================
  {
    id: "he_residence",
    marketId: "higher_ed",
    label: "Residence Hall",
    short: "RES",
    description: "Undergraduate housing — traditional double-loaded, suite, or apartment style with study commons.",
    capacityUom: "BED",
    capacityLabel: "beds",
    defaults: {
      costProfile: "concrete_residential",
      floors: 5, floorToFloor: 10, footprint: { w: 190, d: 62 }, grossing: 1.42,
      glazing: "punched", glazingCoverage: 30, skin: "brick", roof: "flat",
      structure: "concrete", travelDistance: 250, parkingRatio: 0.2,
    },
    plan: "L",
    features: [
      { kind: "canopy", params: { width: 22, projection: 8 } },
      { kind: "lobby", params: { width: 36, projection: 6, floors: 2 } },
    ],
    efficiency: { low: 0.64, typical: 0.7, high: 0.76 },
    unitRefs: ["dorm_double", "dorm_single", "dorm_suite", "dorm_apt", "amen_study"],
    programMix: [
      { unitRef: "dorm_double", share: 0.55 },
      { unitRef: "dorm_suite", share: 0.3 },
      { unitRef: "dorm_single", share: 0.15 },
    ],
    supportSpaces: [
      { unitRef: "amen_study", sfPerCapacity: 14 },
      { unitRef: "amen_lobby", sfPerCapacity: 6 },
    ],
    typicalCapacity: { low: 150, high: 700 },
    tags: ["summer-schedule", "repetitive"],
  },
  {
    id: "he_academic",
    marketId: "higher_ed",
    label: "Academic / Classroom",
    short: "ACAD",
    description: "General instruction — classrooms, seminar rooms, faculty offices, and informal learning space.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "academic",
      floors: 3, floorToFloor: 14, footprint: { w: 170, d: 95 }, grossing: 1.5,
      glazing: "strip", glazingCoverage: 52, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 250, bay: { w: 30, d: 30 },
    },
    features: [
      { kind: "lobby", params: { width: 48, projection: 8, floors: 2 } },
      { kind: "sunshade", params: { coverage: 0.8, projection: 3.5 } },
    ],
    efficiency: { low: 0.58, typical: 0.65, high: 0.71 },
    unitRefs: ["edu_classroom", "edu_lecture", "edu_seminar", "off_faculty", "amen_study"],
    programMix: [
      { unitRef: "edu_classroom", share: 0.45 },
      { unitRef: "off_faculty", share: 0.25 },
      { unitRef: "edu_seminar", share: 0.2 },
      { unitRef: "edu_lecture", share: 0.1 },
    ],
    typicalCapacity: { low: 20000, high: 140000 },
    tags: ["instruction"],
  },
  {
    id: "he_lab",
    marketId: "higher_ed",
    label: "Science / Teaching Lab",
    short: "LAB",
    description: "Wet and dry teaching labs with fume hoods, lab gas, and heavy exhaust. Highest $/SF on campus.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "lab",
      floors: 3, floorToFloor: 16, footprint: { w: 160, d: 100 }, grossing: 1.6,
      glazing: "strip", glazingCoverage: 45, skin: "precast", roof: "flat",
      structure: "concrete", travelDistance: 200, bay: { w: 32, d: 32 },
    },
    features: [
      { kind: "sunshade", params: { coverage: 0.9, projection: 4 } },
      { kind: "roof_screen", params: { coverage: 0.9, material: "louver", height: 14 } },
      { kind: "lobby", params: { width: 40, projection: 7, floors: 2 } },
    ],
    efficiency: { low: 0.5, typical: 0.58, high: 0.65 },
    unitRefs: ["edu_lab_wet", "edu_lab_dry", "edu_classroom", "off_faculty", "edu_maker"],
    programMix: [
      { unitRef: "edu_lab_wet", share: 0.5 },
      { unitRef: "edu_lab_dry", share: 0.25 },
      { unitRef: "off_faculty", share: 0.15 },
      { unitRef: "edu_classroom", share: 0.1 },
    ],
    typicalCapacity: { low: 25000, high: 160000 },
    tags: ["high-MEP", "research"],
  },
  {
    id: "he_student_life",
    marketId: "higher_ed",
    label: "Student Life / Union",
    short: "UNION",
    description: "Dining, lounge, meeting, and student organization space. Long-span assembly with commercial kitchen.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "assembly_longspan",
      floors: 2, floorToFloor: 16, footprint: { w: 180, d: 120 }, grossing: 1.45,
      glazing: "full", glazingCoverage: 62, skin: "curtain_wall", roof: "flat",
      structure: "steel", travelDistance: 250,
    },
    features: [
      { kind: "canopy", params: { width: 34, projection: 12, support: "suspended" } },
      { kind: "lobby", params: { width: 56, projection: 9, floors: 2 } },
    ],
    efficiency: { low: 0.6, typical: 0.66, high: 0.72 },
    unitRefs: ["amen_dining", "amen_kitchen", "amen_lobby", "edu_seminar", "amen_activity"],
    programMix: [
      { unitRef: "amen_dining", share: 0.4 },
      { unitRef: "amen_activity", share: 0.25 },
      { unitRef: "amen_kitchen", share: 0.2 },
      { unitRef: "edu_seminar", share: 0.15 },
    ],
    typicalCapacity: { low: 20000, high: 120000 },
    tags: ["assembly", "food-service"],
  },
  {
    id: "he_athletics",
    marketId: "higher_ed",
    label: "Athletics / Recreation",
    short: "ATH",
    description: "Courts, pool, fitness, and locker space. Long-span structure and high-volume conditioning.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "assembly_longspan",
      floors: 2, floorToFloor: 22, footprint: { w: 220, d: 140 }, grossing: 1.3,
      glazing: "strip", glazingCoverage: 35, skin: "metal_panel", roof: "flat",
      structure: "steel", travelDistance: 400,
    },
    efficiency: { low: 0.68, typical: 0.75, high: 0.8 },
    unitRefs: ["ath_court", "ath_pool", "amen_fitness", "amen_locker"],
    programMix: [
      { unitRef: "ath_court", share: 0.4 },
      { unitRef: "amen_fitness", share: 0.3 },
      { unitRef: "ath_pool", share: 0.2 },
      { unitRef: "amen_locker", share: 0.1 },
    ],
    typicalCapacity: { low: 30000, high: 200000 },
    tags: ["long-span", "natatorium"],
  },
  {
    id: "he_library",
    marketId: "higher_ed",
    label: "Library / Learning Commons",
    short: "LIB",
    description: "Collections, study, and technology commons. Floor loading and daylighting drive the design.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "academic",
      floors: 3, floorToFloor: 14, footprint: { w: 165, d: 110 }, grossing: 1.35,
      glazing: "full", glazingCoverage: 58, skin: "curtain_wall", roof: "flat",
      structure: "concrete", travelDistance: 250,
    },
    features: [
      { kind: "sunshade", params: { coverage: 0.9, projection: 4 } },
      { kind: "lobby", params: { width: 44, projection: 8, floors: 2 } },
    ],
    efficiency: { low: 0.66, typical: 0.72, high: 0.78 },
    unitRefs: ["amen_study", "edu_seminar", "off_private", "amen_lobby"],
    programMix: [
      { unitRef: "amen_study", share: 0.6 },
      { unitRef: "edu_seminar", share: 0.2 },
      { unitRef: "off_private", share: 0.2 },
    ],
    typicalCapacity: { low: 20000, high: 150000 },
    tags: ["daylight", "high-floor-load"],
  },

  // ===================== MULTIFAMILY =====================
  {
    id: "mf_garden",
    marketId: "multifamily",
    label: "Garden Apartments",
    short: "GARDEN",
    description: "Two- to three-story walk-ups on surface parking. The lowest-cost multifamily product.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "wood_residential_walkup",
      floors: 3, floorToFloor: 9.5, footprint: { w: 190, d: 60 }, grossing: 1.22,
      glazing: "punched", glazingCoverage: 24, skin: "fiber_cement", roof: "gable",
      structure: "wood_frame", travelDistance: 250, parkingRatio: 1.6,
    },
    features: [
      { kind: "bay", params: { width: 10, projection: 2 } },
    ],
    efficiency: { low: 0.8, typical: 0.85, high: 0.89 },
    unitRefs: ["apt_studio", "apt_1br", "apt_2br", "apt_3br"],
    programMix: [
      { unitRef: "apt_1br", share: 0.45 },
      { unitRef: "apt_2br", share: 0.4 },
      { unitRef: "apt_3br", share: 0.1 },
      { unitRef: "apt_studio", share: 0.05 },
    ],
    typicalCapacity: { low: 60, high: 300 },
    tags: ["walk-up", "surface-parking", "lowest-cost"],
  },
  {
    id: "mf_wrap",
    marketId: "multifamily",
    label: "Mid-Rise Wrap",
    short: "WRAP",
    description: "Four to five stick-framed stories wrapping a precast parking deck. The suburban workhorse.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "wood_residential",
      floors: 5, floorToFloor: 10, footprint: { w: 260, d: 66 }, grossing: 1.28,
      glazing: "punched", glazingCoverage: 28, skin: "fiber_cement", roof: "flat",
      structure: "wood_frame", travelDistance: 250, parkingRatio: 1.3,
    },
    plan: "U",
    features: [
      { kind: "canopy", params: { width: 20, projection: 7 } },
      { kind: "lobby", params: { width: 30, projection: 5, floors: 1 } },
      { kind: "bay", params: { width: 12, projection: 2.5 } },
    ],
    efficiency: { low: 0.76, typical: 0.82, high: 0.86 },
    unitRefs: ["apt_studio", "apt_1br", "apt_1br_den", "apt_2br", "apt_3br"],
    programMix: [
      { unitRef: "apt_1br", share: 0.5 },
      { unitRef: "apt_2br", share: 0.32 },
      { unitRef: "apt_studio", share: 0.12 },
      { unitRef: "apt_3br", share: 0.06 },
    ],
    supportSpaces: [
      { unitRef: "amen_fitness", sfPerCapacity: 8 },
      { unitRef: "amen_lobby", sfPerCapacity: 6 },
    ],
    typicalCapacity: { low: 150, high: 400 },
    tags: ["wrap", "structured-parking"],
  },
  {
    id: "mf_podium",
    marketId: "multifamily",
    label: "Podium (Type III over I)",
    short: "PODIUM",
    description: "Wood-framed residential over a concrete podium with ground-floor retail or parking.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "podium_residential",
      floors: 6, floorToFloor: 10, footprint: { w: 230, d: 72 }, grossing: 1.3,
      glazing: "punched", glazingCoverage: 32, skin: "fiber_cement", roof: "flat",
      structure: "podium", travelDistance: 250, parkingRatio: 1.0,
    },
    plan: "L",
    features: [
      { kind: "canopy", params: { width: 22, projection: 8 } },
      { kind: "lobby", params: { width: 34, projection: 6, floors: 2 } },
      { kind: "bay", params: { width: 14, projection: 3 } },
    ],
    efficiency: { low: 0.74, typical: 0.8, high: 0.85 },
    unitRefs: ["apt_studio", "apt_1br", "apt_1br_den", "apt_2br", "apt_3br"],
    programMix: [
      { unitRef: "apt_1br", share: 0.48 },
      { unitRef: "apt_2br", share: 0.3 },
      { unitRef: "apt_studio", share: 0.16 },
      { unitRef: "apt_3br", share: 0.06 },
    ],
    supportSpaces: [
      { unitRef: "amen_fitness", sfPerCapacity: 9 },
      { unitRef: "amen_lobby", sfPerCapacity: 7 },
    ],
    typicalCapacity: { low: 120, high: 400 },
    tags: ["podium", "mixed-use"],
  },
  {
    id: "mf_highrise",
    marketId: "multifamily",
    label: "High-Rise",
    short: "HR",
    description: "Concrete tower over structured parking. Vertical transportation and curtain wall drive cost.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "concrete_highrise",
      floors: 18, floorToFloor: 10.5, footprint: { w: 120, d: 80 }, grossing: 1.38,
      glazing: "full", glazingCoverage: 70, skin: "curtain_wall", roof: "flat",
      structure: "concrete", travelDistance: 250, parkingRatio: 0.8, highRise: true,
    },
    features: [
      { kind: "canopy", params: { width: 24, projection: 10, support: "suspended" } },
      { kind: "lobby", params: { width: 42, projection: 7, floors: 2 } },
      { kind: "cornice", params: { depth: 2, projection: 1.5 } },
    ],
    efficiency: { low: 0.7, typical: 0.76, high: 0.81 },
    unitRefs: ["apt_studio", "apt_1br", "apt_2br", "apt_3br", "apt_penthouse"],
    programMix: [
      { unitRef: "apt_1br", share: 0.45 },
      { unitRef: "apt_2br", share: 0.3 },
      { unitRef: "apt_studio", share: 0.18 },
      { unitRef: "apt_3br", share: 0.05 },
      { unitRef: "apt_penthouse", share: 0.02 },
    ],
    supportSpaces: [
      { unitRef: "amen_fitness", sfPerCapacity: 10 },
      { unitRef: "amen_lobby", sfPerCapacity: 9 },
    ],
    typicalCapacity: { low: 150, high: 600 },
    tags: ["high-rise", "curtain-wall"],
  },
  {
    id: "mf_affordable",
    marketId: "multifamily",
    label: "Affordable / LIHTC",
    short: "MF-A",
    description: "Tax-credit family housing under QAP cost caps. Durability over finish level.",
    capacityUom: "UNIT",
    capacityLabel: "apartments",
    defaults: {
      costProfile: "wood_residential",
      floors: 4, floorToFloor: 9.5, footprint: { w: 190, d: 62 }, grossing: 1.24,
      glazing: "punched", glazingCoverage: 24, skin: "fiber_cement", roof: "flat",
      structure: "wood_frame", travelDistance: 250, parkingRatio: 1.1,
    },
    efficiency: { low: 0.78, typical: 0.83, high: 0.88 },
    unitRefs: ["apt_1br", "apt_2br", "apt_3br"],
    programMix: [
      { unitRef: "apt_2br", share: 0.45 },
      { unitRef: "apt_1br", share: 0.35 },
      { unitRef: "apt_3br", share: 0.2 },
    ],
    supportSpaces: [{ unitRef: "amen_community", sfPerCapacity: 10 }],
    typicalCapacity: { low: 40, high: 200 },
    tags: ["LIHTC", "cost-capped"],
  },
  {
    id: "mf_townhome",
    marketId: "multifamily",
    label: "Townhomes",
    short: "TH",
    description: "Attached two- and three-story homes with private entries and garages. Fee-simple or rental.",
    capacityUom: "UNIT",
    capacityLabel: "homes",
    defaults: {
      costProfile: "wood_residential_walkup",
      floors: 3, floorToFloor: 9.5, footprint: { w: 176, d: 34 }, grossing: 1.1,
      glazing: "punched", glazingCoverage: 26, skin: "brick", roof: "gable",
      structure: "wood_frame", travelDistance: 250, parkingRatio: 2.0,
    },
    efficiency: { low: 0.86, typical: 0.9, high: 0.94 },
    unitRefs: ["apt_townhome"],
    programMix: [{ unitRef: "apt_townhome", share: 1 }],
    typicalCapacity: { low: 8, high: 120 },
    tags: ["for-sale", "attached"],
  },

  // ===================== HOSPITALITY =====================
  {
    id: "hp_select",
    marketId: "hospitality",
    label: "Select Service Hotel",
    short: "SEL",
    description: "Limited-amenity branded product — breakfast bar, small fitness, no full kitchen.",
    capacityUom: "KEY",
    capacityLabel: "keys",
    defaults: {
      costProfile: "light_gauge_hospitality",
      floors: 5, floorToFloor: 9.5, footprint: { w: 190, d: 62 }, grossing: 1.35,
      glazing: "punched", glazingCoverage: 30, skin: "fiber_cement", roof: "flat",
      structure: "light_gauge", travelDistance: 250, parkingRatio: 1.0,
    },
    features: [
      { kind: "canopy", params: { width: 26, projection: 12, support: "column" } },
      { kind: "lobby", params: { width: 34, projection: 6, floors: 1 } },
    ],
    efficiency: { low: 0.7, typical: 0.75, high: 0.8 },
    unitRefs: ["hotel_king", "hotel_double", "hotel_suite", "amen_lobby", "amen_fitness"],
    programMix: [
      { unitRef: "hotel_king", share: 0.55 },
      { unitRef: "hotel_double", share: 0.4 },
      { unitRef: "hotel_suite", share: 0.05 },
    ],
    supportSpaces: [
      { unitRef: "amen_lobby", sfPerCapacity: 14 },
      { unitRef: "amen_fitness", sfPerCapacity: 6 },
    ],
    typicalCapacity: { low: 80, high: 160 },
    tags: ["branded", "repetitive"],
  },
  {
    id: "hp_extended",
    marketId: "hospitality",
    label: "Extended Stay",
    short: "EXT",
    description: "Kitchenette suites for long-stay guests. More plumbing and casework per key than select service.",
    capacityUom: "KEY",
    capacityLabel: "keys",
    defaults: {
      costProfile: "light_gauge_hospitality",
      floors: 4, floorToFloor: 9.5, footprint: { w: 185, d: 64 }, grossing: 1.32,
      glazing: "punched", glazingCoverage: 28, skin: "fiber_cement", roof: "flat",
      structure: "light_gauge", travelDistance: 250, parkingRatio: 1.0,
    },
    efficiency: { low: 0.72, typical: 0.77, high: 0.82 },
    unitRefs: ["hotel_studio_suite", "hotel_1br_suite", "amen_lobby"],
    programMix: [
      { unitRef: "hotel_studio_suite", share: 0.75 },
      { unitRef: "hotel_1br_suite", share: 0.25 },
    ],
    typicalCapacity: { low: 90, high: 150 },
    tags: ["branded", "kitchenettes"],
  },
  {
    id: "hp_full",
    marketId: "hospitality",
    label: "Full Service Hotel",
    short: "FULL",
    description: "Ballroom, restaurant, and commercial kitchen alongside guest rooms. Public space drives cost.",
    capacityUom: "KEY",
    capacityLabel: "keys",
    defaults: {
      costProfile: "concrete_hospitality",
      floors: 8, floorToFloor: 10, footprint: { w: 180, d: 80 }, grossing: 1.5,
      glazing: "strip", glazingCoverage: 48, skin: "precast", roof: "flat",
      structure: "concrete", travelDistance: 250, parkingRatio: 0.8, highRise: true,
    },
    features: [
      { kind: "porte_cochere", params: { width: 48, projection: 28, height: 17 } },
      { kind: "lobby", params: { width: 64, projection: 9, floors: 2 } },
      { kind: "cornice", params: { depth: 2.5, projection: 2 } },
    ],
    efficiency: { low: 0.6, typical: 0.66, high: 0.72 },
    unitRefs: ["hotel_king", "hotel_double", "hotel_suite", "amen_ballroom", "amen_kitchen", "amen_dining"],
    programMix: [
      { unitRef: "hotel_king", share: 0.5 },
      { unitRef: "hotel_double", share: 0.42 },
      { unitRef: "hotel_suite", share: 0.08 },
    ],
    supportSpaces: [
      { unitRef: "amen_ballroom", sfPerCapacity: 26 },
      { unitRef: "amen_kitchen", sfPerCapacity: 12 },
      { unitRef: "amen_dining", sfPerCapacity: 14 },
      { unitRef: "amen_lobby", sfPerCapacity: 16 },
    ],
    typicalCapacity: { low: 150, high: 500 },
    tags: ["banquet", "food-service"],
  },
  {
    id: "hp_boutique",
    marketId: "hospitality",
    label: "Boutique / Lifestyle",
    short: "BTQ",
    description: "Design-forward independent product, often adaptive reuse. Bespoke finishes, low repetition.",
    capacityUom: "KEY",
    capacityLabel: "keys",
    defaults: {
      costProfile: "concrete_hospitality",
      floors: 6, floorToFloor: 11, footprint: { w: 130, d: 70 }, grossing: 1.45,
      glazing: "strip", glazingCoverage: 52, skin: "brick", roof: "flat",
      structure: "concrete", travelDistance: 250, parkingRatio: 0.4,
    },
    features: [
      { kind: "canopy", params: { width: 20, projection: 8, support: "suspended" } },
      { kind: "lobby", params: { width: 30, projection: 5, floors: 2 } },
      { kind: "cornice", params: { depth: 2, projection: 1.5 } },
    ],
    efficiency: { low: 0.58, typical: 0.66, high: 0.72 },
    unitRefs: ["hotel_king", "hotel_suite", "amen_dining", "amen_lobby"],
    programMix: [
      { unitRef: "hotel_king", share: 0.8 },
      { unitRef: "hotel_suite", share: 0.2 },
    ],
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 22 },
      { unitRef: "amen_lobby", sfPerCapacity: 20 },
    ],
    typicalCapacity: { low: 40, high: 150 },
    tags: ["adaptive-reuse", "bespoke"],
  },

  // ===================== WORKPLACE =====================
  {
    id: "wk_shell",
    marketId: "workplace",
    label: "Office Core & Shell",
    short: "SHELL",
    description: "Structure, envelope, core, and base building systems — no tenant fit-out.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      scopeMode: "shell",
      costProfile: "office_shell",
      floors: 4, floorToFloor: 14, footprint: { w: 180, d: 110 }, grossing: 1.15,
      glazing: "full", glazingCoverage: 68, skin: "curtain_wall", roof: "flat",
      structure: "steel", travelDistance: 300, bay: { w: 30, d: 40 },
    },
    features: [
      { kind: "canopy", params: { width: 30, projection: 12, support: "suspended" } },
      { kind: "lobby", params: { width: 50, projection: 8, floors: 2 } },
      { kind: "sunshade", params: { coverage: 0.9, projection: 3.5 } },
      { kind: "roof_screen", params: { coverage: 0.5, material: "louver" } },
    ],
    efficiency: { low: 0.82, typical: 0.87, high: 0.91 },
    unitRefs: ["off_open", "off_private", "amen_lobby"],
    programMix: [{ unitRef: "off_open", share: 1 }],
    typicalCapacity: { low: 25000, high: 300000 },
    tags: ["shell-only"],
  },
  {
    id: "wk_fitout",
    marketId: "workplace",
    label: "Office Fit-Out",
    short: "TI",
    description: "Tenant improvement within an existing shell — partitions, finishes, distribution, and furniture.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      scopeMode: "interiors",
      costProfile: "office_fitout",
      floors: 1, floorToFloor: 14, footprint: { w: 150, d: 90 }, grossing: 1.0,
      glazing: "none", glazingCoverage: 0, skin: "fiber_cement", roof: "flat",
      structure: "steel", travelDistance: 300,
    },
    efficiency: { low: 0.8, typical: 0.85, high: 0.9 },
    unitRefs: ["off_open", "off_private", "edu_seminar", "amen_kitchen"],
    programMix: [
      { unitRef: "off_open", share: 0.6 },
      { unitRef: "off_private", share: 0.22 },
      { unitRef: "edu_seminar", share: 0.18 },
    ],
    typicalCapacity: { low: 3000, high: 120000 },
    tags: ["interiors-only"],
  },
  {
    id: "wk_flex",
    marketId: "workplace",
    label: "Flex / R&D",
    short: "FLEX",
    description: "Office front with high-bay production or lab behind. Split systems and split cost per SF.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "flex",
      floors: 1, floorToFloor: 18, footprint: { w: 200, d: 130 }, grossing: 1.15,
      glazing: "strip", glazingCoverage: 32, skin: "metal_panel", roof: "flat",
      structure: "steel", travelDistance: 300, bay: { w: 40, d: 40 },
    },
    features: [
      { kind: "canopy", params: { width: 18, projection: 7 } },
    ],
    efficiency: { low: 0.8, typical: 0.86, high: 0.9 },
    unitRefs: ["off_open", "edu_lab_dry", "ind_highbay"],
    programMix: [
      { unitRef: "ind_highbay", share: 0.6 },
      { unitRef: "off_open", share: 0.3 },
      { unitRef: "edu_lab_dry", share: 0.1 },
    ],
    typicalCapacity: { low: 15000, high: 150000 },
    tags: ["high-bay", "hybrid"],
  },

  // ===================== INDUSTRIAL =====================
  {
    id: "in_warehouse",
    marketId: "industrial",
    label: "Warehouse / Distribution",
    short: "WHSE",
    description: "Tilt-up or precast box with clear height, dock doors, and ESFR sprinkler. Slab is the critical item.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "warehouse",
      floors: 1, floorToFloor: 36, footprint: { w: 500, d: 300 }, grossing: 1.04,
      glazing: "strip", glazingCoverage: 8, skin: "tilt_up", roof: "flat",
      structure: "tilt_up", travelDistance: 400, bay: { w: 50, d: 50 },
    },
    features: [
      { kind: "canopy", params: { width: 20, projection: 8 } },
    ],
    efficiency: { low: 0.92, typical: 0.95, high: 0.97 },
    unitRefs: ["ind_highbay", "off_open", "ind_dock"],
    programMix: [
      { unitRef: "ind_highbay", share: 0.94 },
      { unitRef: "off_open", share: 0.06 },
    ],
    typicalCapacity: { low: 50000, high: 1000000 },
    tags: ["tilt-up", "ESFR", "clear-height"],
  },
  {
    id: "in_manufacturing",
    marketId: "industrial",
    label: "Light Manufacturing",
    short: "MFG",
    description: "Production floor with process power, compressed air, and crane or monorail provisions.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "manufacturing",
      floors: 1, floorToFloor: 28, footprint: { w: 320, d: 220 }, grossing: 1.08,
      glazing: "strip", glazingCoverage: 14, skin: "metal_panel", roof: "flat",
      structure: "steel", travelDistance: 400, bay: { w: 40, d: 40 },
    },
    efficiency: { low: 0.88, typical: 0.92, high: 0.95 },
    unitRefs: ["ind_highbay", "off_open", "ind_dock"],
    programMix: [
      { unitRef: "ind_highbay", share: 0.85 },
      { unitRef: "off_open", share: 0.15 },
    ],
    typicalCapacity: { low: 30000, high: 400000 },
    tags: ["process-power", "crane"],
  },
  {
    id: "in_cold",
    marketId: "industrial",
    label: "Cold Storage",
    short: "COLD",
    description: "Refrigerated warehouse — insulated envelope, underslab heat, and refrigeration plant dominate.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "cold_storage",
      floors: 1, floorToFloor: 40, footprint: { w: 380, d: 260 }, grossing: 1.06,
      glazing: "none", glazingCoverage: 0, skin: "insulated_panel", roof: "flat",
      structure: "tilt_up", travelDistance: 400, bay: { w: 50, d: 50 },
    },
    efficiency: { low: 0.9, typical: 0.94, high: 0.96 },
    unitRefs: ["ind_freezer", "ind_cooler", "ind_dock", "off_open"],
    programMix: [
      { unitRef: "ind_freezer", share: 0.55 },
      { unitRef: "ind_cooler", share: 0.35 },
      { unitRef: "off_open", share: 0.1 },
    ],
    typicalCapacity: { low: 60000, high: 400000 },
    tags: ["refrigeration", "insulated-envelope"],
  },

  // ===================== CIVIC =====================
  {
    id: "cv_k12",
    marketId: "civic",
    label: "K-12 School",
    short: "K12",
    description: "Classrooms, cafeteria, gym, and media center. Public bid, prevailing wage, summer schedule.",
    capacityUom: "STUDENT",
    capacityLabel: "students",
    defaults: {
      costProfile: "academic",
      floors: 2, floorToFloor: 14, footprint: { w: 240, d: 130 }, grossing: 1.5,
      glazing: "strip", glazingCoverage: 42, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 250, parkingRatio: 0.2,
    },
    plan: "L",
    features: [
      { kind: "canopy", params: { width: 30, projection: 12, support: "column" } },
      { kind: "lobby", params: { width: 40, projection: 6, floors: 2 } },
    ],
    efficiency: { low: 0.58, typical: 0.65, high: 0.71 },
    unitRefs: ["edu_classroom", "edu_lab_wet", "amen_dining", "ath_court", "amen_study"],
    programMix: [
      { unitRef: "edu_classroom", share: 0.62 },
      { unitRef: "edu_lab_wet", share: 0.12 },
      { unitRef: "amen_study", share: 0.14 },
      { unitRef: "edu_seminar", share: 0.12 },
    ],
    gsfPerCapacity: 165,
    supportSpaces: [
      { unitRef: "amen_dining", sfPerCapacity: 9 },
      { unitRef: "ath_court", sfPerCapacity: 7 },
    ],
    typicalCapacity: { low: 300, high: 2000 },
    tags: ["public-bid", "prevailing-wage"],
  },
  {
    id: "cv_worship",
    marketId: "civic",
    label: "Worship",
    short: "WOR",
    description: "Sanctuary with fellowship, education, and administration. Long-span assembly plus AV.",
    capacityUom: "SEAT",
    capacityLabel: "seats",
    defaults: {
      costProfile: "assembly_longspan",
      floors: 1, floorToFloor: 20, footprint: { w: 160, d: 120 }, grossing: 1.4,
      glazing: "punched", glazingCoverage: 22, skin: "brick", roof: "gable",
      structure: "steel", travelDistance: 250, parkingRatio: 0.3,
    },
    features: [
      { kind: "porte_cochere", params: { width: 34, projection: 20 } },
    ],
    efficiency: { low: 0.62, typical: 0.7, high: 0.76 },
    unitRefs: ["civ_sanctuary", "edu_classroom", "amen_activity", "amen_kitchen"],
    programMix: [
      { unitRef: "civ_sanctuary", share: 0.55 },
      { unitRef: "amen_activity", share: 0.25 },
      { unitRef: "edu_classroom", share: 0.2 },
    ],
    gsfPerCapacity: 28,
    typicalCapacity: { low: 200, high: 2000 },
    tags: ["assembly", "long-span"],
  },
  {
    id: "cv_municipal",
    marketId: "civic",
    label: "Municipal / Public Safety",
    short: "MUNI",
    description: "Town halls, police, and fire stations. Essential-facility structure and backup power.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "civic_essential",
      floors: 2, floorToFloor: 15, footprint: { w: 150, d: 100 }, grossing: 1.45,
      glazing: "punched", glazingCoverage: 30, skin: "brick", roof: "flat",
      structure: "steel", travelDistance: 250,
    },
    features: [
      { kind: "canopy", params: { width: 28, projection: 12, support: "column" } },
      { kind: "cornice", params: { depth: 2.5, projection: 2 } },
    ],
    efficiency: { low: 0.6, typical: 0.67, high: 0.73 },
    unitRefs: ["off_private", "off_open", "edu_seminar", "civ_apparatus"],
    programMix: [
      { unitRef: "off_open", share: 0.45 },
      { unitRef: "off_private", share: 0.25 },
      { unitRef: "civ_apparatus", share: 0.2 },
      { unitRef: "edu_seminar", share: 0.1 },
    ],
    typicalCapacity: { low: 8000, high: 80000 },
    tags: ["essential-facility", "public-bid"],
  },
  {
    id: "cv_recreation",
    marketId: "civic",
    label: "Community Recreation",
    short: "REC",
    description: "Municipal rec center — gym, pool, multipurpose, and community rooms.",
    capacityUom: "SF",
    capacityLabel: "square feet",
    defaults: {
      costProfile: "assembly_longspan",
      floors: 1, floorToFloor: 22, footprint: { w: 200, d: 140 }, grossing: 1.32,
      glazing: "strip", glazingCoverage: 38, skin: "metal_panel", roof: "flat",
      structure: "steel", travelDistance: 400,
    },
    features: [
      { kind: "canopy", params: { width: 26, projection: 10 } },
      { kind: "lobby", params: { width: 40, projection: 7, floors: 1 } },
    ],
    efficiency: { low: 0.68, typical: 0.74, high: 0.8 },
    unitRefs: ["ath_court", "ath_pool", "amen_fitness", "amen_activity", "amen_locker"],
    programMix: [
      { unitRef: "ath_court", share: 0.35 },
      { unitRef: "ath_pool", share: 0.25 },
      { unitRef: "amen_fitness", share: 0.2 },
      { unitRef: "amen_activity", share: 0.2 },
    ],
    typicalCapacity: { low: 20000, high: 120000 },
    tags: ["natatorium", "long-span"],
  },

  // ===================== PARKING =====================
  {
    id: "pk_garage",
    marketId: "parking",
    label: "Structured Garage",
    short: "DECK",
    description: "Above-grade precast or cast-in-place deck. Priced per stall, carried as separate scope.",
    capacityUom: "STALL",
    capacityLabel: "stalls",
    defaults: {
      scopeMode: "structure",
      costProfile: "parking_structure",
      floors: 5, floorToFloor: 10.5, footprint: { w: 190, d: 122 }, grossing: 1.0,
      glazing: "none", glazingCoverage: 0, skin: "precast", roof: "flat",
      structure: "concrete", travelDistance: 400,
    },
    efficiency: { low: 0.95, typical: 0.98, high: 1.0 },
    unitRefs: ["pk_stall"],
    programMix: [{ unitRef: "pk_stall", share: 1 }],
    typicalCapacity: { low: 200, high: 1200 },
    tags: ["per-stall", "precast"],
  },
  {
    id: "pk_below",
    marketId: "parking",
    label: "Below-Grade Parking",
    short: "SUB",
    description: "Subterranean levels under a building. Excavation, shoring, and waterproofing dominate.",
    capacityUom: "STALL",
    capacityLabel: "stalls",
    defaults: {
      scopeMode: "structure",
      costProfile: "parking_below",
      belowGrade: true,
      floors: 2, floorToFloor: 11, footprint: { w: 180, d: 120 }, grossing: 1.0,
      glazing: "none", glazingCoverage: 0, skin: "precast", roof: "flat",
      structure: "concrete", travelDistance: 400,
    },
    efficiency: { low: 0.92, typical: 0.96, high: 0.99 },
    unitRefs: ["pk_stall"],
    programMix: [{ unitRef: "pk_stall", share: 1 }],
    typicalCapacity: { low: 60, high: 500 },
    tags: ["per-stall", "excavation", "waterproofing"],
  },
  {
    id: "pk_surface",
    marketId: "parking",
    label: "Surface Parking",
    short: "SURF",
    description: "At-grade paving, striping, lighting, and stormwater. The cheapest stall by an order of magnitude.",
    capacityUom: "STALL",
    capacityLabel: "stalls",
    defaults: {
      scopeMode: "site",
      costProfile: "parking_surface",
      floors: 1, floorToFloor: 0, footprint: { w: 300, d: 200 }, grossing: 1.0,
      glazing: "none", glazingCoverage: 0, skin: "precast", roof: "flat",
      structure: "steel", travelDistance: 400,
    },
    efficiency: { low: 1, typical: 1, high: 1 },
    unitRefs: ["pk_stall"],
    programMix: [{ unitRef: "pk_stall", share: 1 }],
    typicalCapacity: { low: 20, high: 800 },
    tags: ["per-stall", "sitework"],
  },
];
